### ISSUE TITLE
Sufficiently new cmake should be preferred over cmake3

### ISSUE THREAD

**Issue by ngoldbaum** [scikit-build/scikit-build#1066]
I'm helping someone debug an issue building some software in a conda environment. The package they're building uses scikit-build and they happen to have a `/usr/bin/cmake3` executable in their PATH. See [here](https://github.com/Point72/csp/issues/73).

Because of [these lines](https://github.com/scikit-build/scikit-build/blob/bbd0bd0436d85951386292c3413027d4364319d7/skbuild/constants.py#L26-L27) in scikit-build, the `/usr/bin/cmake3` executable is always found first before the `cmake` executable on the user's `PATH` that comes from the `conda-forge` `cmake` package. The `cmake` package doesn't install a `cmake3` binary.

@henryiii suggested that we should first check for `cmake` and if it's sufficiently new use that, and otherwise fall back to cmake3. This will preserve compatibility with old RHEL setups where cmake is really old but cmake3 works.

_Originally posted by @ngoldbaum in https://github.com/conda-forge/scikit-build-feedstock/issues/78_

**Comment by henryiii** [comment]
Actually, I was thinking scikit-build-core; it's a little tricker in scikit-build, since we don't have the minimum version set were we can read it in the old system. Maybe we could either select `cmake` if it's >3, otherwise look for `cmake3`, or select the newest of the pair? I believe `cmake` is the official command, and `cmake3` is only a RHEL addition since they wanted to have LTS support for CMake 2.8.

I'm not sure what our lowest supported version is (scikit-build-core is 3.15, but I think scikit-build currently supports a lot less, possibly 2.8).
