### ISSUE TITLE
Creating a Wheel package that installs on "site-packages" and "dist-packages" directories 

### ISSUE THREAD

**Issue by atilag** [scikit-build/scikit-build#387]
The problem I have is that it seems like this line:
```
install(TARGETS my_extension LIBRARY DESTINATION ${PYTHON_RELATIVE_SITE_PACKAGES_DIR})
```
will install `my_exntesion.so` on `site-packages` directory, even on Debian based distros. Unfotunately, Debian based distros use a differente naming nomenclature, and they use `dist-packages` instead, so the Python interpreters on Debian based distros can't load my extensions unless I add the `dist-packages` directory to the `sys.path` before, which is pretty hackish I'd say.

Is there a way to create a wheel package that is agnostic to this `site/dist-pacakges` problem?
Thanks!

Awesome project guys!!

**Comment by jcfr** [comment]
Hi @atilag ,

Thanks for the kind words :smile: 


> Is there a way to create a wheel package that is agnostic to this `site/dist-pacakges` problem?

Instead of using

```
install(TARGETS my_extension LIBRARY DESTINATION ${PYTHON_RELATIVE_SITE_PACKAGES_DIR})
```

I suggest you use something like:


```
install(TARGETS my_extension LIBRARY DESTINATION name_of_project)
```

where `name_of_project` is the python package name.

This is similar to the `hello` package name used in this [example](https://scikit-build.readthedocs.io/en/latest/usage.html#example-of-setup-py-cmakelists-txt-and-pyproject-toml), the corresponding `setup.py` can also be found in the [hello-cpp](https://github.com/scikit-build/scikit-build-sample-projects/tree/master/projects/hello-cpp) sample project.

**Comment by atilag** [comment]
Thanks! It worked perfectly.
Love this easy fixes :)
