### ISSUE TITLE
Shared libraries, RPATH, and dependencies

### ISSUE THREAD

**Issue by blowekamp** [scikit-build/scikit-build#39]
I am looking for information on planned shared library support.

How are RPATHs going to be handled? Is it going to have be to specified correctly at compilation time? or can it be fixed up during installation and packaging time?

How are dependent shared libraries going to be handled? If my project depends on another large project, is there an easy way to get those dependent libraries installed and packaged with the correct RPATHs?

**Comment by opadron** [comment]
Hi, @blowekamp.

Short version:
  1. RPATHS are not handled at all
  2. yes (sort of)
  3. yes (sort of)

Longer version:

RPATH handling is one of the tricky parts that we're still trying to figure out.

We are depending on some information inferred from the CMake project in order to package things correctly.  The main issue is that most of that information is derived from the project's install manifest file that is only created after the `cmake install` step.  So what we're doing at the moment is setting aside a predetermined staging directory, setting that as the CMake install prefix, and hijacking the install mechanism to produce the manifest prior to packaging.

Unfortunately, we give up on taking advantage of CMake's RPATH handling, since it thinks it's installing to the staging directory and therefore sets the wrong RPATHs, and then we give up on any RPATH handling that distutils might give us since by the time it comes into play, all the binaries are built and already in place (most of them are treated as generic `data_files`).

So, we could implement a post-install step that would fix RPATHs.  That should help you if you're installing a package manually from source, but for binary packages, we're completely stuck because the issue is out of our control at that stage; AFAIK, there's no mention of how RPATHS are handled in python wheels, which is where RPATHS would have to be handled since we can't know how to set them until package installation.

So far, what I've been doing during development is setting `(DY)LD_LIBRARY_PATH` for SHARED libs, but I agree proper RPATH support would be ideal.  I'm just not sure where (if at all) we might find that support.

**Comment by opadron** [comment]
For some more info: here's what the first [draft PEP](https://mail.python.org/pipermail/distutils-sig/2016-January/027997.html) for the `manylinux1` platform tag has to say about shared libraries:

```
Most desktop and server linux distributions come with a system package manager
(examples include ``APT`` on Debian-based systems, ``yum`` on
``RPM``-based systems, and ``pacman`` on Arch linux) that manages, among other
responsibilities, the installation of shared libraries installed to system
directories such as ``/usr/lib``. Most non-trivial Python extensions will depend
on one or more of these shared libraries, and thus function properly only on
systems where the user has the proper libraries (and the proper
versions thereof), either installed using their package manager, or installed
manually by setting certain environment variables such as ``LD_LIBRARY_PATH``
to notify the runtime linker of the location of the depended-upon shared
libraries.
```

Further down they talk about their proposed strategy, which skirts around the RPATH issue by bundling the libraries in question along with the rest of the package in a single wheel.  I can't say I'm a fan of this idea, but in any case it goes to show the kinds of lengths we'd have to take to completely automate the RPATH problem away.

**Comment by 7starsea** [comment]
I found that in my case I solved this problem by initializing [CMAKE_INSTALL_RPATH](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_RPATH.html) in CMakeLists.txt.
May this help you, too.

Aimin

**Comment by winni2k** [comment]
Hey @7starsea, I think I might have the same problem. Can you share some code showing how you initialized the CMAKE_INSTALL_RPATH in your case?

**Comment by 7starsea** [comment]
> Hey @7starsea, I think I might have the same problem. Can you share some code showing how you initialized the CMAKE_INSTALL_RPATH in your case?

 I am using conda, so find out the conda env lib dir first (I think it's primarly python runtime lib path)
```
if(SKBUILD)
    set(CMAKE_INSTALL_RPATH "${CONDA_ENV_LIB_DIR}")
    message(STATUS "Using scikit-build, RPATH:${CMAKE_INSTALL_RPATH}")
endif()
```
Hope it helps.

**Comment by winni2k** [comment]
Thanks! I'm running through virtualenv, and this got me a bit closer. Unfortunately, I could not get it to work so I have given up on this.
