### ISSUE TITLE
Windows default generator selection is still wrong.

### ISSUE THREAD

**Issue by opadron** [scikit-build/scikit-build#44]
While working on #43, I made the following observation:

> The windows generator selection logic does not work near line 37:
```Python
if platform.architecture() == "x64":
```
> The code should be able to handle tuples and other spellings of "64 bit".  For example, on my home machine running windows 7, I get:
```
>>> platform.architecture()
('64bit', 'WindowsPE')
```

**Comment by opadron** [comment]
So, considering how inexact of a science these sorts of things tend to be, I'd propose the following heuristic for better detection of 64-bit Python on Windows:

  - If `platform.architecture()` is a tuple, consider its elements; if it is *not* a tuple, consider a one-element tuple with `platform.architecture()` as the sole element.

  - Search through each element for a case-insensitive match to one of a number of predefined strings resembling the presence of a 64-bit environment.

  - If at least one match is found, proceed with a 64-bit generator selection.

  - Predefined strings may include `"64"`, `"64bit"`, `"64 bit"`, `"64-bit"`, or `"x64"`

#### and/or

We could just use the struct module to check the size of a pointer, just like I did in the [driver script](https://github.com/opadron/scikit-build/blob/ab0d4bc4c5c9a033a506196199f2b920738cfb6c/ci/appveyor/driver.py#L150-L152)

**Comment by jcfr** [comment]
This is fixed in https://github.com/scikit-build/scikit-build/commit/ed21cb7df34e640fe4a4dab39392583999aa8500

In both python 2 and 3, the string are consistently return `32bit` or `64bit`, see [here](https://github.com/python/cpython/blob/d818b305dc4b3d7115c1fd3c0432c1dd54e22078/Lib/platform.py#L1087-L1094) for 2.7 and [here](https://github.com/python/cpython/blob/62e67e667e0a34f1efa559a7294f9af583b3d043/Lib/platform.py#L918-L925) for 3.x
