### ISSUE TITLE
Cleanup wheels from useless artefacts

### ISSUE THREAD

**Issue by SylvainCorlay** [scikit-build/scikit-build#473]
Is it possible to exclude  items which are in the cmake install manifest from the wheel?

As it turns out, we were able to do a fully static build of everything in our scikit-build wheel to avoid relocation issues, but te resulting wheel includes the `.a`, as well as the cmake config files and other artefacts from the dependencies. Since all we produce is an executable, we could completely remove all of that...

**Comment by jcfr** [comment]
Thanks for the report.

Since scikit-build performs the install of the project, I suspect they are install rules associated with static libraries.

To address this, I am thinking of few possible approaches:
* (1) provide a scikit-build specific option allowing to choose components to install. We should then be able to only  install these.  I think we could achieve this by improving the parse_manifest function used [here](https://github.com/scikit-build/scikit-build/blob/0c33f15b0c0452e8bd70ab6057b4d283d6025b51/skbuild/cmaker.py#L509-L513)
* (1a) If scikit-build detect they are components associated with install rules, it could automatically select `Runtime` and `RuntimeLibraries` components by building up on what would be implemented in (1)... but I fear this will break existing packages.
* (2) Systematically filter out some of the artifacts based on file extension.

I think (1) would be a reasonable trad-off.

**Comment by SylvainCorlay** [comment]
I think that (1) and then (1a) at a later stage are probably the best way to do so.

If there was a hook to filter items in the manifest manually, we would certainly do that for now.
