### ISSUE TITLE
Update requirements files to fix info reported by requires.io

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#573]
As of August 4th, visiting  https://requires.io/github/scikit-build/scikit-build/requirements/?branch=master reports that setuptools and sphinx are outdated. For future reference, see screenshot below.

* `setuptools`: Add `  # rq.filter: <45` (see documentation of requires filter [here](https://requires.io/features/)). Indeed, as explained in  https://github.com/scikit-build/scikit-build/commit/a0cbcedea94514a92f3f9230825379fca2128fbd, an older setuptools needs to be used for python < 3.

* `sphinx`: @henryiii , in https://github.com/scikit-build/scikit-build/commit/9087b5defc1d4c29ec6933fea4fd20d26468dc04 you added a constraint for not using the latest sphinx. Do you recall the rational for doing so ?

---------------

#### scikit-build readme file

![image](https://user-images.githubusercontent.com/219043/128127925-f40d8991-38fb-496a-9486-1a7a971efa79.png)

#### requires.io website

![image](https://user-images.githubusercontent.com/219043/128127840-f758355a-1cb6-48fd-8ad7-c432e40e1261.png)

**Comment by henryiii** [comment]
### Setuptools

This is a false positive; we pin setuptools only for Python 2, since 45+ is Python 3 only. Since Pip 8, this has been handled correctly by Pip; it will read the Requires-Python metadata slot and select the most recent compatible setuptools, so really, we could drop it and be just fine today. But if we plan to drop Python 2 support in 4 months or less, then not sure it's worth changing. I'd be fine either way - I don't pin like this in any other package, and have had no problems.

### Sphinx

This is docs-only, so it does not affect users. And Sphinx is very slow to be supported by all it's plugins - IIRC, sphinx-rtd-theme is behind (it usually is) for the update. It might have only been warnings, though, don't remember, from looking at the theme it seems it just produces a bunch of warnings with Sphinx 4.

We really should consider a new theme for our docs, IMO. The PyPA is using [Furo](https://github.com/pradyunsg/furo), which is clean and supports dark mode - this includes packages like Pip and Setuptools. Data science packages are using [pydata-sphinx-theme](https://pydata-sphinx-theme.readthedocs.io/en/latest/), which is highly customizable - it's defining features is the links across the top, which NumPy and co use to toggle between Install / Documentation / Community and such. And there's also [sphinx-book-theme](https://github.com/executablebooks/sphinx-book-theme), which is similar to the pydata one, and is developed for JupyterBook. Pybind11 is considering a new theme from these choices as well.

Visually Furo is my favorite, though I'm going to try pydata on pybind11 too just to see what it's like when configured. I'd recommend monitoring https://github.com/pybind/pybind11/pull/3109 and making a decision after seeing what comes up there.

**Comment by henryiii** [comment]
Removing the limit produces:

```
nox -s docs -- serve
nox > Running session docs
nox > Creating virtual environment (virtualenv) using python3.9 in .nox/docs
nox > python -m pip install -r requirements-docs.txt
nox > python -m pip install .
nox > cd docs
nox > sphinx-build -M html . _build
Running Sphinx v4.1.2

Extension error:
Could not import extension cmake (exception: cannot import name 'htmlescape' from 'sphinx.util.pycompat' (/Users/henryschreiner/git/software/scikit-build/.nox/docs/lib/python3.9/site-packages/sphinx/util/pycompat.py))
nox > Command sphinx-build -M html . _build failed with exit code 2
nox > Session docs failed.
```
