### ISSUE TITLE
CMake fails to find ninja on second build from pip when installed via build-requires

### ISSUE THREAD

**Issue by segevfiner** [scikit-build/scikit-build#628]
When building a project a second time using `pip install -e .`, cmake will fail to find ninja with the following error:
```
Failed to build whatever:
     'C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-m4knfc7v/overlay/Scripts/ninja.exe' '--version'
    
      failed with:
    
       The system cannot find the file specified
```

This is caused by pip removing its temporary `pip-build-env` directory between the builds, and cmake not trying to look for ninja again despite it not existing.

OS: Windows 10.0.19044.0

**Comment by RUrlus** [comment]
I am running into the same issue on MacOS, the issue also occurs without the editable install `-e` flag.
Ninja, CMake and Python build dependencies are cached in `_skbuild/macosx-10.15-x86_64-3.8/cmake-build/CMakeCache.txt` for example:
```
//Program used to build from build.ninja files.
CMAKE_MAKE_PROGRAM:FILEPATH=/private/var/folders/pr/fgvttt6572xg2szn4s3c3tnw0000gn/T/pip-build-env-2_zfozp2/overlay/bin/ninja
```

I came up with two work-arounds:

#### Replace paths in build directory files

This approach keeps the CMake cache otherwise intact, it will still recompile but quicker than deleting the build directory.

```python
import re
from pathlib import Path
import skbuild
from skbuild import setup

def update_pip_build_env_path(base_path):
    """Replace path to temporary pip-build-env directory in build directory files."""
    pip_env_re = re.compile("^//.*$\n^[^#].*pip-build-env.*$", flags=re.M)
    pip_env_path = skbuild.__path__[0].split('lib')[0]
    replace_pattern = None
    for obj in Path(base_path).rglob("*"):
        content = None
        if obj.is_file():
            try:
                content = obj.read_text()
            except UnicodeDecodeError:
                continue
        if content is not None:
            match = re.search(pip_env_re, content)
            if match:
                if replace_pattern is None:
                    # if it exists grab it
                    string = match.group(0)
                    # extract the start of path in the string as marked by the first 5
                    # characters of the replacement path
                    path_with_postfix = ''.join(string.partition(pip_env_path[:5])[1:])
                    # find the end of the path in the string as marked by the last 5
                    # characters of the replacement path
                    replace_pattern = re.compile(
                        ''.join(path_with_postfix.partition(pip_env_path[-5:])[:-1])
                    )
                # replace all instances of the old path with the new pip_env_path
                content = re.sub(replace_pattern, pip_env_path, content)
                obj.write_text(content)


if __name__ == '__main__':
    # fix issue with CMake cache when building in-tree multiple times
    # https://github.com/scikit-build/scikit-build/issues/628
    build_dir_path = (
        Path(skbuild.constants.CMAKE_BUILD_DIR())
    )
    if build_dir_path.exists():
        update_pip_build_env_path(build_dir_path)

    setup(
        ...
```
#### Delete build directory

```python
import re
import shutil
from pathlib import Path
import skbuild
from skbuild import setup

if __name__ == '__main__':
    # fix issue with CMake cache when building in-tree multiple times
    # https://github.com/scikit-build/scikit-build/issues/628
    build_dir = Path(skbuild.constants.SKBUILD_DIR())
    if build_dir.exists():
        shutil.rmtree(build_dir)
    setup(
        ...
```

**Comment by henryiii** [comment]
Hmm, I think we can use a couple of things to make this a bit more focused of a fix. First, we only need to do this if the ninja python package is installed - ninja shouldn't be moving if coming from the system, just in Python. Second, I think only updating `CMAKE_MAKE_PROGRAM` is likely safe - in fact, if ninja is present, we could just always populate it, since we know it.

@jcfr If there's a way to tell CMake to rediscover the same generator if it's moved, that would be what we need here. But I think manually setting it is likely fine.

**Comment by segevfiner** [comment]
@henryiii Maybe if you just clear the `CMAKE_MAKE_PROGRAM` CMake cache variable. It might just be running this to find ninja: https://github.com/Kitware/CMake/blob/master/Modules/CMakeNinjaFindMake.cmake.

`cmake -U CMAKE_MAKE_PROGRAM` maybe? But I haven't tested this.

**Comment by jcfr** [comment]
> cmake -U CMAKE_MAKE_PROGRAM maybe? But I haven't tested this.

Exactly. That will do it. I confirmed this works on Linux.

**Comment by henryiii** [comment]
I've added #631 - this will manually set `CMAKE_MAKE_PROGRAM` to the ninja executable if ninja is selected and the ninja package is installed. That should work too?

**Comment by RUrlus** [comment]
> Hmm, I think we can use a couple of things to make this a bit more focused of a fix. First, we only need to do this if the ninja python package is installed - ninja shouldn't be moving if coming from the system, just in Python.

The above approach accounts for this, only the python packages should end up in `/some/temp/dir/pip-build-env-2_*/overlay/...`
However, the same issue occurs for all python packages that are installed pre-build using isolation
```
# e.g. cmake wheel
CMAKE_MODULE_PATH:PATH=/private/var/folders/pr/fgvttt6572xg2szn4s3c3tnw0000gn/T/pip-build-env-f3n5dxqh/overlay/lib/python3.8/site-packages/skbuild/resources/crake

# or if you are passing Pybind11:
//No help, variable specified on the command line.
pybind11_DIR:STRING=/private/var/folders/pr/fgvttt6572xg2szn4s3c3tnw0000gn/T/pip-build-env-f3n5dxqh/overlay/lib/python3.8/site-packages/pybind11/share/cmake/pybind11
```
That's why the fix doesn't just look in the `CMakeCache.txt` this path shows up in:
* cmake-build/CMakeFiles/rules.ninja
* cmake-build/build.ninja
* cmake-build/CMakeSpec.json
* ...

Just removing `CMAKE_MAKE_PROGRAM` removes the error but it doesn't allow incremental builds on my system which I was hoping to get with the above fix.

**Comment by henryiii** [comment]
Should you be using build isolation and expecting incremental builds? I'd expect build-isolation to _work_ (which the ninja command was breaking), but if it just does more rebuilding than expected, I don't think that's too bad for now. You can disable build isolation if you want fast builds - as it's already slower at the expense of being "correct".

Ideally, we could save the current directory, then just transform it old->new on a subset of known files (*.ninja, *.CMake, CMakeSpec.json, etc). But for now I think this is a solid step forward. Or possibly always delete the cache on build-isolation builds, and just assume those are never supposed to be "fast", but instead correct (would also help with #633). I don't currently think this is the best way to go, but could change.

**Comment by RUrlus** [comment]
> Should you be using build isolation and expecting incremental builds?
Fair point, although it's become pretty much the standard with `pyproject.toml` being the advocated route everywhere.
I would argue that editable builds should not be using isolation by default, but that's not Scikit-build's responsibility.

Regardless, thanks for the quick fix!
