### ISSUE TITLE
GCC is automatically detected on Windows instead of MSVC

### ISSUE THREAD

**Issue by planetmarshall** [scikit-build/scikit-build#650]
This appears to be a recent change as some CI builds have started failing and the scikit-build version is the only thing that has changed.

Reproduced on Azure Devops windows-2019 host (agent version 2.198.2) Using cibuildwheel 2.3.0

## Log from failing build (scikit-build 0.13)

```
2022-02-02T20:00:32.1865951Z -- The C compiler identification is GNU 8.1.0
2022-02-02T20:00:32.5689077Z -- Detecting C compiler ABI info
2022-02-02T20:00:33.4125739Z -- Detecting C compiler ABI info - done
2022-02-02T20:00:33.4369218Z -- Check for working C compiler: C:/ProgramData/chocolatey/bin/gcc.exe - skipped
2022-02-02T20:00:33.4378665Z -- Detecting C compile features
2022-02-02T20:00:33.4392321Z -- Detecting C compile features - done
2022-02-02T20:00:38.2725206Z -- The CXX compiler identification is GNU 8.1.0
```

## Log from working build (scikit-build 0.12)

```
2022-02-02T17:42:38.5825398Z -- The C compiler identification is MSVC 19.29.30139.0
2022-02-02T17:42:38.6379084Z -- Detecting C compiler ABI info
2022-02-02T17:42:45.2473535Z -- Detecting C compiler ABI info - done
2022-02-02T17:42:45.2500227Z -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x64/cl.exe - skipped
2022-02-02T17:42:45.2510064Z -- Detecting C compile features
2022-02-02T17:42:45.2522927Z -- Detecting C compile features - done
2022-02-02T17:42:49.2204422Z -- The CXX compiler identification is MSVC 19.29.30139.0
```

Placeholder until I can provide a minimal example.

## Workaround

Pin `scikit-build` at 0.12

**Comment by henryiii** [comment]
The correct workaround is to activate the MSVC vars before building on windows, but okay. I thought this was specific to 2019+, since that was the version that added Ninja, and this is using ninja but finding GCC instead, and passing the check somehow. But it appears to be related to the addition of 2022 if pinning 0.12 "fixes" it.

**Comment by henryiii** [comment]
Actually, I think the problem is that if the maximum MSVC isn't found, then it's resorting to GCC. So we used to have a max of 2019, which usually was found, now it's 2022, so that's why 2019 images are failing. We have a workaround for this for the 2016 image as we only recently became sensitive to the found compiler being MSVC in our tests.

**Comment by maxbachmann** [comment]
> The correct workaround is to activate the MSVC vars before building on windows, but okay

How can this be achieved when building with cibuildwheels in Github Actions?

**Comment by henryiii** [comment]
```yaml
     - uses: ilammy/msvc-dev-cmd@v1
       if: runner.os == 'Windows'
```

with: toolset: can be used to pick a version.

**Comment by planetmarshall** [comment]
> The correct workaround is to activate the MSVC vars before building on windows, but okay. I thought this was specific to 2019+, since that was the version that added Ninja, and this is using ninja but finding GCC instead, and passing the check somehow. But it appears to be related to the addition of 2022 if pinning 0.12 "fixes" it.

Yes, wasn't sure if this was really a bug in scipy but it's a change in behaviour that may cause some "surprise" so thought it worth logging.

**Comment by henryiii** [comment]
It's not the intended behavior; it's supposed to try to find the latest MSVC if one isn't activated. Activation is how you control it normally, we just try to do the "best" thing, and that's broken. I've partially fixed it so far in #653.

**Comment by maxbachmann** [comment]
@henryiii thanks for the help. This worked fine. I only had to differentiate between x86 and x86_64 (https://github.com/maxbachmann/RapidFuzz/blob/main/.github/workflows/releasebuild.yml).

**Comment by henryiii** [comment]
`"ninja; platform_system!='Windows'"` in your pyproject.toml should fix the problem too, I think. The problem is we now force the local ninja, and the local ninja finds GCC, while the one that ships with MSVC finds MSVC. More details in the linked PR, and hopefully I'll have a fix soon - though I'd still recommend not installing ninja on Windows - it's not needed anyway, and even ships with MSVC these days.

**Comment by maxbachmann** [comment]
> "ninja; platform_system!='Windows'" in your pyproject.toml should fix the problem too, I think

Yes: https://github.com/maxbachmann/RapidFuzz/commit/8639df9a68ddee3f0ede5cfaaab19bc4de525a04 works :+1:

**Comment by henryiii** [comment]
I recommend `ninja; platform_system!='Windows'` anyway, since MSVC already ships with Ninja, so there's no point in using a local Ninja. I think we can in the future fix the MSVC activation to handle local Ninja correctly, but for now, it will fall back on the IDE generator if Ninja doesn't find the proper one. Will ship a patch release soon.

**Comment by henryiii** [comment]
FYI, 0.13.1 is out.
