### ISSUE TITLE
Evaluate use of `target_link_libraries( <name> [PUBLIC|PRIVATE|INTERFACE] )`

### ISSUE THREAD

**Issue by robertmaynard** [scikit-build/scikit-build#709]
CMake 2.18.X introduced the concept of usage requirements to linking. This allow projects to specify non public usage requirements.
scikit-build uses the non explicit version of `target_link_libraries` which can't be mixed with `target_link_libraries( <name> [PUBLIC|PRIVATE|INTERFACE] )` ( https://cmake.org/cmake/help/latest/policy/CMP0023.html ).

This is problematic for a couple of reasons:

- All best practises of CMake avoid the usage of non PUBLIC/PRIVATE/INTERFACE signatures to `target_link_libraries`
- It stops targets generated by scikit-build to use `INTERFACE` libraries ( `add_library(<name> INTERFACE)` ) as they can only be referenced by the usage-requirement version

While this would be a breaking change to scikit-build, I expect it would be a welcome improvement as it aligned the project with the expected behavior of CMake projects.

**Comment by henryiii** [comment]
Currently it's opt-in as of 0.13.0+ #611 with `SKBUILD_LINK_LIBRARIES_KEYWORD`. I'd like to redesign the CMake modules to be more like the pybind11 ones (and use FindPython, possibly require FindPython; in fact, FindPython alone might be enough to replace the extensions module and Cython module) as part of https://iscinumpy.dev/post/scikit-build-proposal/; there are quite a lot of issues due to age with the current modules. Personally I have avoided them and used pybind11's modules instead.

**Comment by robertmaynard** [comment]
> Guessing you meant 2.8.x unless there's a secret internal fork I don't know about. ;D

I meant 2.8.12 

>  in fact, FindPython alone might be enough to replace the extensions module and Cython module) as part of https://iscinumpy.dev/post/scikit-build-proposal/; 

In that case, I am going to close this issue as it seems largely unneeded.
