### ISSUE TITLE
Fix python setup.py build sdist

### ISSUE THREAD

**Issue by thewtex** [scikit-build/scikit-build#84]
Currently this creates a tarbal with the contents of _skbuild/cmake-install.
Instead, it should contain the project source code so that the sdist can be
downloaded and a platform-specific binary wheel can be created from it.

**Comment by opadron** [comment]
I'm taking a look at this now, and the way to handle this is not trivial.  Distutils and setuptools expect to have information about extension modules and their sources. Because we're preempting their build logic, we're effectively removing the information that they need to correctly produce a source package.

We would need to provide our own mechanism for identifying the files that should be included in an sdist tarball.  One possibility is to include (yet another) CMake module with a function that you would call on each of your source files.  Then, we can configure the build and inspect the output of that function without having to actually build anything.

I'm open to other ideas.

**Comment by blowekamp** [comment]
Currently SimpleITK has a script files it uses to create tar ball [1].

The important thing to determine is what is needed to enable pip to be able to download, build and install from a source or tarball. 

[1] https://github.com/SimpleITK/SimpleITK/blob/master/Utilities/Maintenance/SourceTarball.bash

**Comment by opadron** [comment]
Basically, we need packages that use skbuild to provide their own version of "install_manifest.txt", but for their sources.  It could be a created by the CMake project, a package-specific script, or just a flat text file.

**Comment by blowekamp** [comment]
Do you have an example of this structure where the "install_manifest.txt" is used for the source tarball?

From scikit-build
python setup.py sdist && tar -ztvf ./dist/scikit-build-0.2.0.tar.gz  |grep install

I don't see install_manifest.txt in sdist?

**Comment by jcfr** [comment]
For reference, here is the documentation:
* https://docs.python.org/2/distutils/sourcedist.html#specifying-the-files-to-distribute
* https://docs.python.org/3/distutils/sourcedist.html#specifying-the-files-to-distribute

**Comment by opadron** [comment]
Right, I forgot distutils was already doing this!

So, it looks like the best solution is to simply not change the paths to the various `packages` declared in the `setup()` call, and require folks to provide their own MANIFEST(.in).

If so, this would be much less work than I had originally feared! :)

**Comment by thewtex** [comment]
Could we generate a sensible default if not explicitly present? If `.git/` is present, then the output of `git archive` would be a good default. If `.git/` is not present, then all sources excluding `dist/` and `_skbuild` would be a good default.

If those defaults do not work for projects, then they could write a MANIFEST.in file...

**Comment by opadron** [comment]
@thewtex yes, that sounds reasonable to me.

**Comment by thewtex** [comment]
Checking current master, this issue has yet to be addressed.

**Comment by opadron** [comment]
@thewtex That's right.  sdist handling is still on the todo list.

But, building wheels from a manual checkout should work.
