### ISSUE TITLE
CMake integration issues

### ISSUE THREAD

**Issue by LecrisUT** [scikit-build/scikit-build#840]
There are a few minor comments for the cmake integration and documentation:
- [ ] We should rely on bundled cmake python integration, e.g. [`find_package(Python COMPONENTS NumPy)`](https://cmake.org/cmake/help/latest/module/FindPython.html). From [my testing](https://github.com/spglib/spglib/pull/210/commits/004e7a4ed78b3c055fa9eb0ced5ea56c1dd1d68e), to integrate that, we only need to provide appropriate `Python_EXECUTABLE` option.
- [ ] `PythonExtensions` seems to be provided by us instead of finding system third-party library. So this should be changed to a `PythonExtensionsConfig.cmake` instead and provide versions for the API changes.
- [ ] Related to #834, we should default to system cmake libraries instead of bundled version when possible. Relevant code [here](https://github.com/scikit-build/scikit-build/blob/66b523d2ee9fa6fd5c38067421762724b3c6afab/skbuild/cmaker.py#L282)
- [ ] Include `cmake` as a dependency and bundle it for CI tested versions. Then use appropriate cmake version like in the previous point. Relevant code [here](https://github.com/scikit-build/scikit-build/blob/66b523d2ee9fa6fd5c38067421762724b3c6afab/skbuild/cmaker.py#L148)
- [ ] Some `Use...` should be included in the `Find...` or `...Config` files. Otherwise/For now, document that one must use for example `include(UsePythonExtensions)` in their cmake project

**Comment by henryiii** [comment]
> we only need to provide appropriate Python_EXECUTABLE option

Last I checked, if you specify too many `Python_*` variables, FindPython breaks due to running into a logical error. That needs to be fixed (this was around 3.20 or so, and it's changed since, so might already be fixed). I'll look into it in the near future. Though the current variables we do set should mostly work for FindPython, unless you have a unusually configured environment.

> `PythonExtensions`

This is just a collection of tools that are part of scikit-build that help with the classic FindPythonInterp/Libs. Not sure that these should be versioned separately unless they were pulled out into an optional helper module (which is not out of the question).

> system cmake libraries

CMake is not designed to run if it doesn't match the exact version of its libraries. It's completely invalid to run cmake 3.23 with 3.24's or 3.22's libraries. We shouldn't touch this - whatever we find, that's the libraries we should use.

> Include cmake as a dependency and bundle it for CI tested versions

This will break any platform we don't have binaries for, like WebAssembly, FreeBSD, Android, ClearLinux, and probably many more. We can't depend on the Python CMake package or any binary CMake package.


I recommend looking at scikit-build-core. The correct solution to packaging cmake/ninja for Python is to build it into the PEP 517 interface. In scikit-build-core, it will use the system CMake if it is sufficient, and will dynamically add "cmake" or "ninja" if it's not present, and it's user controllable. That way "weird" systems work by installing CMake via their own package managers, and users can specify they need 3.20+ or some other minimum version.

> include(UsePythonExtensions) 

I don't recommend using PythonExtensions if possible. If you use pybind11, the tools there are better than PythonExtentions even if you are using FindPythonLibs/Interp. Also, FindPython supersedes PythonExtensions, so hopefully once CMake 3.15+ is required, PythonExtensions will fade into a distant memory.

**Comment by LecrisUT** [comment]
> Last I checked, if you specify too many `Python_*` variables, FindPython breaks due to running into a logical error.

Indeed that why I think we should switch to using `Python_EXECUTABLE` only. But indeed it needs to be confirmed more thoroughly.

>> `PythonExtensions`
>
> This is just a collection of tools that are part of scikit-build that help with the classic FindPythonInterp/Libs. Not sure that these should be versioned separately unless they were pulled out into an optional helper module (which is not out of the question).

Indeed that's why it should be a `Config` instead of a `Find` (we are providing it). As for versioning, we can tie it to `scikit-build` version, i.e. in a main `CMakeLists.txt`, read the version of `scikit-build` from the `pyproject.toml` or so on and set `PythonExtensions_VERSION` accordingly.  Also shouldn't we rename/alias is to `scikit-build` instead?

> CMake is not designed to run if it doesn't match the exact version of its libraries. It's completely invalid to run cmake 3.23 with 3.24's or 3.22's libraries. We shouldn't touch this - whatever we find, that's the libraries we should use.

Fair point. I think we should use a flag `use_bundled_cmake` to switch between one or the other. But let's discuss that in #834.

> This will break any platform we don't have binaries for, like WebAssembly, FreeBSD, Android, ClearLinux, and probably many more. We can't depend on the Python CMake package or any binary CMake package.

Isn't that a pip issue? Can we conditionally add dependencies depending on OS?

> In scikit-build-core, it will use the system CMake if it is sufficient, and will dynamically add "cmake" or "ninja" if it's not present, and it's user controllable.

Is this decided at installation time, at the cmake/setup.py execution time, etc.? If the first one, I think there will still be some ambiguity depending on the order of installations of system `scikit-build` and `cmake`. An appropriate `use_bundled_cmake` flag should resolve that ambiguity.

> I don't recommend using PythonExtensions if possible.

Actually the functions might be better than stated. Some projects use some old way of python binding by manually compiling the python api. These are easier to migrate using the `PythonExtensions`, e.g. they don't require `#include <pybind11/pybind11.h>`. I agree that they should migrate to such methods, but I still encourage providing these as less destructive migration paths. See spglib/spglib#210 on an example of that.

**Comment by henryiii** [comment]
> `Python_EXECUTABLE` only

Ahh, that's what you meant. No, that doesn't work, we tried it. IIRC it can't find the Python headers and or library from a virtualenv, as they are in different places.

> instead of a Find

Shouldn't it be just `include(PythonExtensions)`? We aren't really finding anything, it's just some extra files. And you can't get the version from somewhere other than scikit-build, since it's built into scikit-build.

For versioning, scikit-build-core reports its version, you can get that. You shouldn't have to get PythonExtensions.

> Isn't that a pip issue? Can we conditionally add dependencies depending on OS?

No, it's supported by PEP 517 `get_requires_for_build_wheel` hook. A build system can decide what dependencies it needs based on the system - scikit-build-core and meson-python already do this, and it works really well. This happens during pip or build's (any PEP 517 builder) build process. It happens during the build process. You can also manually control it by not building in isolation then choosing to install cmake or ninja.

This should not be a flag that a user passes in configuration, since a user doesn't control what platform they are on when they are writing setup.py. This has already been solved in scikit-build-core and meson-python, it's just not available here yet.

I'd highly recommend trying scikit-build-core out directly and seeing if you still see issues. :)

> These are easier to migrate using the

We will try to have a reasonable path forward for project using FindPythonLibs/Interp heavily, but I'm not sure PythonExtensions will be the best way to do that. Unless it's causing a major issue now, I'd rather move forward with scikit-build-core and focus on FindPython for a bit, and working on this once there's a good use case for supporting deprecated FindPythonInterp/Libs with helpers in scikit-build-core. Happy to fix things that are broken before then, though. (Things like #703 make me want to avoid it).

**Comment by LecrisUT** [comment]
> Shouldn't it be just `include(PythonExtensions)`?

`find_package` looks for both `FindPythonExtensions.cmake` and `PythonExtensionsConfig.cmake`. For third party scripts, it should generally be this instead of using `include(...)` (or maybe it should be `find_package` and then `include`? didn't look at other examples that provide macros).

> No, it's supported by PEP 517 get_requires_for_build_wheel hook. A build system can decide what dependencies it needs based on the system

Perfect. Then we can bundle cmake for suitable systems

> This should not be a flag that a user passes in configuration, since a user doesn't control what platform they are on when they are writing setup.py

I think it would be useful to have it as a flag. The user can switch between the system or virtual environment cmake, the latter which we can test compatibility with different versions. If bundled version is passed, it should not pick up the system's files, but otherwise we can override it with `CMAKE_MODULE_PATH`.

> I'd rather move forward with scikit-build-core and focus on FindPython for a bit

I will test scikit-build-core if it fixes the pip install issues I had with plain `FindPython`. The issue I had was if I had a `CMakeLists.txt` file with:
```cmake
find_package(Python REQUIRED COMPONENTS Interpreter Development NumPy)
Python_add_library(python_api SHARED _foo.c)
target_link_libraries(python_api PRIVATE foo Python::NumPy)
set_target_properties(python_api PROPERTIES
		OUTPUT_NAME _foo
		PREFIX "")
install(TARGETS foo LIBRARY DESTINATION foo)
install(TARGETS python_api LIBRARY DESTINATION foo)
```

The system generates `_foo.so`. However, according to `PEP 3149`, it should include the full `SOABI` from `sysconfig.get_config_var('SOABI')`. Currently this is not included for libraries other than `MODULE`.

I don't know if it is really appropriate or not for shared libraries since `pip install .` seems to work with that also. For now I use the following workaround to include appropriate `SOABI`:
```cmake
find_package(Python REQUIRED COMPONENTS Interpreter Development NumPy)
find_package(PythonExtensions REQUIRED)
include(UsePythonExtensions)
add_python_extension(_foo
		SOURCES _foo.c
		LINK_LIBRARIES foo Python::NumPy)
install(TARGETS foo LIBRARY DESTINATION foo)
#install(TARGETS _foo LIBRARY DESTINATION foo)
```

**Comment by LecrisUT** [comment]
Got a bit more understanding of the `MODULE` and python api, and it is correct that only `MODULE` type libraries should have `SOABI` (i.e. external C code should not link to those python API). My issues were red-herrings with installation directory. After that the build became much more cleaner, and indeed `scikit-build-core` looks like a proper way to build going forward.

It raises the question though what will be the purpose of this project instead?

**Comment by henryiii** [comment]
Ah, sorry, I could have responded about FindPython, you have to add the `WITH_SOABI` option to `Python_add_library(... MODULE WITH_SOABI)` to get the soabi added. And the soabi it adds is incorrect for PyPy (fixed in the upcoming CMake release, will be backported in scikit-build-core). Scikit-build-core helps workaround this issue with the `SKBUILD_SOABI` variable, see the example.

Scikit-build-core will become a dependency for scikit-build, and there will be a setuptools plugin for scikit-build-core that will power classic builds for scikit-build. Eventually, scikit-build will probably become a frontend for scikit-build-core (the backend).
